package de.mealdeal.service.recommendation;

/** Machine-readable explanations that can be localized by a future UI. */
public enum RecommendationReasonCode {
    RECIPE_HARD_EXCLUDED,
    INGREDIENT_GROUP_HARD_EXCLUDED,
    DISH_TYPE_MISMATCH,
    MISSING_REQUIRED_INGREDIENT_STRUCTURE,
    HARD_EXCLUDED_ALTERNATIVE_IGNORED,
    PANTRY_FULL_COVERAGE,
    PANTRY_MOSTLY_COVERED,
    PANTRY_LOW_COVERAGE,
    MISSING_ONE_INGREDIENT_GROUP,
    MISSING_MULTIPLE_INGREDIENT_GROUPS,
    ALTERNATIVE_AVAILABLE,
    TASTE_STRONG_MATCH,
    TASTE_MATCH,
    TASTE_MISMATCH,
    TIME_WITHIN_LIMIT,
    TIME_OVER_LIMIT,
    TIME_UNKNOWN,
    HOUSEHOLD_STRONG_MATCH,
    HOUSEHOLD_MEMBER_DISLIKES,
    RECENTLY_COOKED,
    VARIETY_BONUS
}
